service: web-app-123

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 128
  timeout: 10
functions:
  source:
    handler: source.handler
    description: function description
    
